server.port=9001

# Configurations H2
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

# Actuator
management.endpoints.web.exposure.include=health,info,refresh

# Configuration externalisee
mes-configs.limitDeProduits=3
